// <auto-generated />
using System;
using ITPLibrary.Api.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITPLibrary.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITPLibrary.Api.Data.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Buyers")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "JRR Tolkien",
                            Buyers = 350,
                            CategoryName = "Fantasy",
                            Description = "An amazing fantasy book!",
                            IsPopular = true,
                            NumberOfPages = 420,
                            Price = 50m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fblogs.slj.com%2Fafuse8production%2Ffiles%2F2012%2F06%2FHobbit9.jpg&f=1&nofb=1",
                            Title = "Hobbit"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Cristopher Nolan",
                            Buyers = 230,
                            CategoryName = "SF",
                            Description = "To galaxy and beyond",
                            IsPopular = true,
                            NumberOfPages = 200,
                            Price = 30m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.platekompaniet.no%2Fglobalassets%2Ffilmcover%2F2015%2Fmars%2Finterstellardvd.jpg&f=1&nofb=1",
                            Title = "Interstellar"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Invatamantul",
                            Buyers = 999,
                            CategoryName = "Drama",
                            Description = "Sadness",
                            IsPopular = true,
                            NumberOfPages = 999,
                            Price = 999m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FYC_MgG7s378%2Fmaxresdefault.jpg&f=1&nofb=1",
                            Title = "Recapitulare bac"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "JRR Tolkien",
                            Buyers = 350,
                            CategoryName = "Fantasy",
                            Description = "An amazing fantasy book! 2",
                            IsPopular = false,
                            NumberOfPages = 320,
                            Price = 50m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.ictv.org.uk%2Fwp-content%2Fuploads%2F2013%2F01%2FThe-Hobbit.jpg&f=1&nofb=1",
                            Title = "Hobbit 2"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Cristopher Nolan",
                            Buyers = 230,
                            CategoryName = "SF",
                            Description = "To galaxy and beyond 2",
                            IsPopular = false,
                            NumberOfPages = 300,
                            Price = 40m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.pandatooth.com%2Fwp-content%2Fuploads%2F2016%2F03%2FInterstellar.jpg&f=1&nofb=1",
                            Title = "Interstellar 2"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Invatamantul",
                            Buyers = 999,
                            CategoryName = "Drama",
                            Description = "Sadness 2",
                            IsPopular = false,
                            NumberOfPages = 399,
                            Price = 499m,
                            ThumbnailUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.christianartgifts.com%2Fproduct-images%2FKJV019_5--featureA.jpg%3Fresizeid%3D5%26resizeh%3D1200%26resizew%3D1200&f=1&nofb=1",
                            Title = "Recapitulare bac 2"
                        });
                });

            modelBuilder.Entity("ITPLibrary.Api.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ITPLibrary.Api.Data.Entities.Book", b =>
                {
                    b.HasOne("ITPLibrary.Api.Data.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
